[package]
name = "slosh3d"
authors = ["Sébastien Crozet <sebcrozet@dimforge.com>"]
description = "Cross-platform GPU 3D Material Point Method implementation."
repository = "https://github.com/dimforge/slosh"
version = "0.7.0"
edition = "2024"
license = "Apache-2.0"

[lints]
workspace = true

[lib]
name = "slosh3d"
path = "../../src/lib.rs"
required-features = ["dim3"]

[features]
default = ["dim3", "rapier-f32", "cpic", "node_particle_lists"]
dim3 = []
cpic = []
node_particle_lists = []

rapier-f32 = ["dep:rapier3d", "rapier"]
rapier-f64 = ["dep:rapier3d-f64", "rapier"]
rapier = []

comptime = ["stensor/comptime", "slosh_testbed3d/comptime"]
runtime = ["stensor/runtime", "slosh_testbed3d/runtime"]
webgpu = ["stensor/webgpu", "slosh_testbed3d/webgpu"]

[dependencies]
glam = { workspace = true }
wgpu = { workspace = true }
encase = { workspace = true }
bytemuck = { workspace = true }
slang-hal = { workspace = true }
stensor = { workspace = true }
static_assertions = { workspace = true }
regex = "1"
bvh = "0.12.0"

serde = "1"

rapier3d = { version = "0.32", optional = true }
rapier3d-f64 = { version = "0.32", optional = true }

[dev-dependencies]
futures-test = "0.3"
serial_test = "3"
approx = "0.5"
async-std = { version = "1", features = ["attributes"] }
slosh_testbed3d = { path = "../slosh_testbed3d" }
kiss3d = { version = "0.37.0" }

[build-dependencies]
minislang = "0.4"
include_dir = "0.7"
slang-hal-build = "0.4"
